### ISSUE TITLE
canvas_test.py: TypeError

### ISSUE THREAD

**Issue by micahcochran** [karimbahgat/PyAgg#3]
```
micah@micah-VirtualBox:~/PyAgg-master$ python canvas_tester.py 
Traceback (most recent call last):
  File "canvas_tester.py", line 195, in <module>
    test_text()
  File "canvas_tester.py", line 36, in test_text
    canvas.draw_axis("x", 0, 140, 0, 25, ticklabeloptions={"textsize":30, "rotate":40, "anchor":"sw","fillcolor":"white"})
  File "/home/micah/PyAgg-master/pyagg/canvas.py", line 1178, in draw_axis
    for x in xpos:
TypeError: 'int' object is not iterable
```

This happens on Linux and Windows using Python 2.7.

**Comment by karimbahgat** [comment]
This looks like an issue of not having updated the test file following changes to the API. The test files as of right now are not very structured and not very frequently run. The entire library in general is still quite fluid as I add more features and fix bugs, although I am definitively getting closer to a version that I might want to solidify and add more proper documentation and testing to. I do appreciate the extra pair of eyes, and I don't have much experience with unittests, so any additions of those would be especially appreciated. 

But for now I updated the test file and added docstring to the draw_axis() method. 

https://github.com/karimbahgat/PyAgg/commit/52cf86a97873e0e55a60f97fd28ace0d6f4d03d4
