### ISSUE TITLE
pip install failed on linux(ubuntu and centos)

### ISSUE THREAD

**Issue by oeway** [karimbahgat/PyAgg#4]
I am trying to install on linux, but get an error:

Downloading PyAgg-0.1.zip (753kB)
    100% |################################| 757kB 157kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/PyAgg.egg-info
    writing pip-egg-info/PyAgg.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/PyAgg.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/PyAgg.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/PyAgg.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

```
error: package directory 'pyagg\fontTools' does not exist

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4nQOTm/pyagg
```

It's not convenient for me to clone the repository and run setup.py, would be great if you can fix the pip problem, thanks in advance.

**Comment by karimbahgat** [comment]
Sorry for the delay @oeway. I finally got around to releasing a new version 0.2.0 on pipy, so you should now be able to use pip to install a version that (hopefully) has mac and linux support (plus many other undocumented feature additions).
